# Generated by Django 3.0 on 2020-09-08 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Preço')),
                ('data_da_criacao', models.DateField(verbose_name='Data')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiitulo', to='blog.Categoria')),
            ],
        ),
    ]
