# Generated by Django 3.0 on 2020-09-08 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='blog.Categoria'),
        ),
    ]
